package eu.kanade.tachiyomi.megaplugin

import org.gradle.api.Project
import java.io.File

class SourceSetGenerator {

    fun generate(project: Project, repo: ScannedRepository, resolvedDeps: ResolvedDependencies) {
        val srcDirs = mutableListOf<File>()
        val resDirs = mutableListOf<File>()
        val assetsDirs = mutableListOf<File>()

        val genAssetsDir = File(project.rootDir, "mega-app/build/generated/mega-assets")
        if (genAssetsDir.exists()) {
            genAssetsDir.deleteRecursively()
        }
        genAssetsDir.mkdirs()

        fun getNamespace(dir: File): String? {
            val relativePath = dir.relativeTo(project.rootDir).path.replace('\\', '/')
            if (relativePath.startsWith("src/")) {
                val parts = relativePath.split("/")
                if (parts.size >= 3) {
                    return "${parts[1]}_${parts[2]}"
                }
            }
            if (relativePath.startsWith("lib-multisrc/")) {
                val parts = relativePath.split("/")
                if (parts.size >= 2) {
                    return "multisrc_${parts[1]}"
                }
            }
            if (relativePath.startsWith("lib/")) {
                val parts = relativePath.split("/")
                if (parts.size >= 2) {
                    return "lib_${parts[1]}"
                }
            }
            return null
        }

        fun addSourceSet(dir: File) {
            val srcDir = File(dir, "src")
            if (srcDir.exists()) srcDirs.add(srcDir)
            val resDir = File(dir, "res")
            if (resDir.exists()) resDirs.add(resDir)
            
            val assetsDir = File(dir, "assets")
            if (assetsDir.exists()) {
                val ns = getNamespace(dir)
                if (ns != null) {
                    val targetDir = File(genAssetsDir, ns)
                    assetsDir.copyRecursively(targetDir, overwrite = true)
                    assetsDirs.add(assetsDir)
                }
            }
        }

        // Load exclusion list
        val excludedFile = File(project.rootDir, "mega-app/mega-excluded-sources.txt")
        val excludedPatterns = if (excludedFile.exists()) {
            excludedFile.readLines()
                .map { it.trim() }
                .filter { it.isNotEmpty() && !it.startsWith("#") }
        } else emptyList()

        fun isExcluded(dir: File): Boolean {
            val path = dir.relativeTo(project.rootDir).path.replace('\\', '/')
            return excludedPatterns.any { pattern -> path.contains(pattern) }
        }

        // Add extensions sources
        repo.extensions.filter { !isExcluded(it) }.forEach { addSourceSet(it) }

        // Add multisrc themes sources
        repo.multisrcThemes.forEach { addSourceSet(it) }

        // Add required libraries sources
        resolvedDeps.libs.forEach { addSourceSet(it) }

        val listFile = File(project.rootDir, "mega-app/mega-sources-list.txt")
        val gradleFile = File(project.rootDir, "mega-app/mega-sources.gradle")
        
        // Write the list file
        val listBuilder = StringBuilder()
        listBuilder.appendLine("# java")
        srcDirs.forEach { listBuilder.appendLine(it.relativeTo(File(project.rootDir, "mega-app")).path.replace('\\', '/')) }
        listFile.writeText(listBuilder.toString())
        
        // Write the static groovy file that dynamically parses the list
        val gradleContent = """
            // GENERATED BY MEGAPLUGIN
            def javaDirs = []
            def listFile = file("mega-sources-list.txt")
            if (listFile.exists()) {
                listFile.eachLine { line ->
                    line = line.trim()
                    if (line.isEmpty() || line.startsWith("#")) {
                        return
                    }
                    javaDirs.add(file(line))
                }
            }
            println "MegaSources: Loaded " + javaDirs.size() + " directories."

            android {
                sourceSets {
                    main {
                        java.srcDirs(javaDirs)
                        kotlin.srcDirs(javaDirs)
                        assets.srcDirs(file("build/generated/mega-assets"))
                        println "MegaSources: Actual java.srcDirs size = " + java.srcDirs.size()
                    }
                }
            }
        """.trimIndent()
        
        gradleFile.writeText(gradleContent)
        project.logger.lifecycle("MegaPlugin: Generated ${srcDirs.size} source dirs and namespaced ${assetsDirs.size} asset dirs under ${genAssetsDir.path}")
    }
}
