name: Build Mega Extension App

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build Type'
        required: true
        default: 'Release'
        type: choice
        options:
          - Release
          - Debug
  schedule:
    - cron: '0 0 */3 * *' # Every 3 days

jobs:
  build:
    name: Build Mega App
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: ${{ github.event.inputs.build_type || 'Release' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Build Mega App APK
        run: ./gradlew :mega-app:assemble${BUILD_TYPE} --no-daemon

      - name: Get lowercased build type
        id: string
        run: echo "BUILD_TYPE_LOWER=$(echo $BUILD_TYPE | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MegaExtensionApp-${{ env.BUILD_TYPE }}
          path: mega-app/build/outputs/apk/${{ env.BUILD_TYPE_LOWER }}/*.apk
